version: '3'
services:
  db:
    image: mysql:8.0.22
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    command: --innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password
    user: "1000:50"
    links:
      - phpmyadmin
  web:
    build: .
    environment:
      TZ: Asia/Tokyo
    command: /bin/sh -c "rm -f ./tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/conpath
    ports:
      - "3000:3000"
    links:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 8080:80
    volumes:
      - /phpmyadmin